### ISSUE TITLE
PATH order should take priority even if coqidetop.opt is before coqidetop 

### ISSUE THREAD

**Issue by andres-erbsen** [whonore/Coqtail#113]
It looks like `launch` in `xmlInterface.py` the  above already tries both `coqidetop` and `coqidetop.opt`. However, prefer `coqidetop` over `coqidetop.opt` even if `coqidetop` is earlier in `PATH`. This means that adding a `coqidetop.opt` to PATH does not change coqtail to use it if `coqidetop` is already on the system path. This currently occurs when building coq master with dune.

**Comment by whonore** [comment]
I think #114 fixes this, but I'm having trouble getting coq to compile with dune locally, so it would be great if you could confirm if it works for you.
