### ISSUE TITLE
Add more configuration options for mappings

### ISSUE THREAD

**Issue by whonore** [whonore/Coqtail#115]
In particular:
- `g:coqtail_noimap` to disable all insert-mode mappings
- `g:coqtail_map_prefix` to customize `<leader>c`

This will avoid annoying delays when `<leader>` is mapped to something common like `<SPACE>` (https://github.com/whonore/Coqtail/issues/93#issuecomment-656762958).

**Comment by paldepind** [comment]
I don't think Coqtail should add insert-mode mappings to the leader per default. Using space as the leader is very popular, and the typing delay that it causes is quite intrusive. I think the setting should be to _enable_ the insert-mode leader bindings.

I do think insert mode bindings are very useful, but maybe they could exists with less intrusive defaults? What about adding them with `CTRL-C` as the prefix in insert mode?

**Comment by whonore** [comment]
I see your point, but I'm hesitant to change the default in case there are people using the current insert-mode mappings. I'll think about it some more and add some set of configuration options soon (enable/disable insert mappings, change the prefix, maybe change the prefix for just insert mappings).
