### ISSUE TITLE
s:coqversion() needs to check for `system` status code

### ISSUE THREAD

**Issue by avp** [whonore/Coqtail#128]
This is a bug that reproduces when the user specifies neither `coqtail_coq_path` nor `coqtail_coq_prog`.

7a306c161b107649d436c07a7dc5bce994162ca2 adds an `s:default_coqs` array which results in `s:coqversion()` looking for `coqtop.opt` first. If `coqtop.opt` does not exist, then `exepath(l:coq)` will be `''`, and the system call: ` --version` will be run, which results in a `bash` error message. On my machine, `l:raw_version` ends up looking something like:
```
['/bin/bash:', '--version:', 'command', 'not', 'found'] 
```

This means that the `if l:version_raw != []` check passes, because `l:version_raw` is not `[]`. So the loop breaks and doesn't attempt to look for the rest of the files in `s:default_coqs`. Then, it doesn't early return because `l:version_raw != []`, so it continues on and provides the uninformative error message:
```
Coqtail does not officially support your version of Coq (/bin/bash:). Continuing with the interface for the latest supported version (8.12).                          
Failed to launch Coq. Invalid version: /bin/bash: 
```

It seems that the fix is probably to make sure the `system` call didn't exit with nonzero exit status (`v:shell_error`) to ensure that the value of `l:version_raw` is actually useful. I verified that changing `if l:version_raw != []` to `if !v:shell_error && l:version_raw != []` fixes it on my machine, but I'll let someone more familiar with Vimscript actually verify that that's the right thing to do.

Reproduced with:
NVIM v0.4.3 and VIM 8.0 (patches 1-1453)
Ubuntu 18.04.4 LTS (bionic) - WSL
coq 8.6 installed via `sudo apt-get install coq`

**Comment by whonore** [comment]
Thanks for reporting and for the detailed steps to reproduce. For some reason with my shell set to fish I just get an empty string from `system` with a non-existent command so I'm glad you caught this.
