### ISSUE TITLE
is there a way to make the highlight less green

### ISSUE THREAD

**Issue by alok** [whonore/Coqtail#133]
Under my colorscheme (solarized dark), the green highlight for the already proved region is way too bright and I can't make out what it says.

**Comment by whonore** [comment]
The colors for the proved region are defined by `CoqtailSent` (proving in progress) and `CoqtailChecked` (proving complete). You can override the defaults by putting something like the following in your .vimrc (or init.vim for NeoVim).
```vim
hi CoqtailChecked ctermbg=19 guibg=LightBlue
hi CoqtailSent ctermbg=90 guibg=Gray
```

**Comment by alok** [comment]
Thanks
