### ISSUE TITLE
_coqproject with neovim?

### ISSUE THREAD

**Issue by licynthiax** [whonore/Coqtail#135]
hi! im encountering an issue where coqproject won't compile my files automatically? as described in issue #42, l:proj_args and :Coq Print LoadPath both print out correctly. ive tried going through my plugins/conf and removing everything but im still getting a `Unable to locate library MyProj.A. (While searching for a .vos file.)` error. im on nvim 0.4.3.

(im really new to coq and nvim so sorry if im missing something!)

**Comment by whonore** [comment]
Coqtail won't automatically compile files for you, although that could be a possible feature to add (I think maybe ProofGeneral does this?). Instead, before you can `Require Import A`, you need to compile A.v either manually with `coqc` (not recommended if you have more than a couple files), or using [`coq_makefile`](https://coq.github.io/doc/master/refman/practical-tools/utilities.html?highlight=makefile#building-a-coq-project-with-coq-makefile) to generate a Makefile based on your `_CoqProject`.

**Comment by licynthiax** [comment]
oh ok, i misunderstood what the plugin does. thanks!
