### ISSUE TITLE
Changing indication for current line.

### ISSUE THREAD

**Issue by Hoblovski** [whonore/Coqtail#14]
The plugin is great to use, as it offers experience in vim like native Coq IDE ;P

I would like to know which lines have already been proved, so I always know where I am.
Does Coqtail offer this feature? I see CoqIDE and coquille have this feature, and for Coqtail when I enable cursorline I can see indications at the end of line when I place the cursor onto a line that is already proved. But I would like the indication to work even if cursorline is not enabled. Also I would like it to be clearer e.g. different bgcolor for proven / unproven lines.

Is it easy to do this in Coqtail?

**Comment by Hoblovski** [comment]
I see in `coqtail.vim` that this maybe has been done.
```
    hi default CheckedByCoq ctermbg=17 guibg=LightGreen
    hi default SentToCoq ctermbg=60 guibg=LimeGreen
```

But it does not work for me, checked lines does not have green background.
I'm using vim 7.4 with python3, and Coq 8.4pl4.

**Comment by Lysxia** [comment]
What I see currently ("proved" lines in blue):

![sc-2019-04-01T13:13:51-04:00](https://user-images.githubusercontent.com/2515201/55346268-18322f80-5480-11e9-8a4b-a89928d777e0.png)

Is this what you are looking for? (I have no idea what could be the problem, but I'm on vim 8.1)

**Comment by whonore** [comment]
Thanks for opening this issue, I'm glad you find Coqtail useful. Those two lines you mentioned are supposed to highlight the lines that have already been proved like in Lysxia's screenshot. If it's not doing that for you it could be some issue with syntax highlighting and your version of vim or one of your settings. I'll look into it soon and let you know what I come up with.

**Comment by Hoblovski** [comment]
@whonore I found the problem to be related to some xterm setting...

After I modified the lines from
```
    hi default CheckedByCoq ctermbg=17 guibg=LightGreen
    hi default SentToCoq ctermbg=60 guibg=LimeGreen
```
to
```
    hi default CheckedByCoq ctermbg=lightgreen guibg=Green
    hi default SentToCoq ctermbg=lightblue guibg=LimeGreen
```

and then the highlight worked well.


Although I don't know why my xterm (in fact it's ubuntu's gnome-terminal) is unhappy with the cterm color numbers :(

**Comment by whonore** [comment]
d9b488d1d3201f9fd96f7c16329711913cd48cc8 should make it so 8/16-color terminals get highlighting that is visible to them.

**Comment by Hoblovski** [comment]
That does really work.
