### ISSUE TITLE
feature request: no formatting in comments

### ISSUE THREAD

**Issue by licynthiax** [whonore/Coqtail#142]
hi! i use comments to take notes and autoformatting often is annoying to fix as im typing. could autoformatting not apply to comments?

**Comment by whonore** [comment]
Sure, that would be nice to have as an option. I'll need to think a bit about the best way of exposing the option and how/if it should interact with other Vim formatting options (`comments`, `formatoptions`, etc), but for the meantime here's a quick patch that should leave comments alone while indenting.

```patch
diff --git a/indent/coq.vim b/indent/coq.vim
index 3e399f0..88b076d 100644
--- a/indent/coq.vim
+++ b/indent/coq.vim
@@ -163,6 +163,10 @@ function! GetCoqIndent() abort
   let l:previousline = substitute(getline(l:lnum), '(\*.*\*)\s*$', '', '')
   let l:currentline = getline(v:lnum)
 
+  if synIDattr(synID(v:lnum, 1, 0), 'name') =~? 'comment'
+    return -1
+  endif
+
   " current line begins with '.':
   if l:currentline =~# '^\s*\.'
     return s:indent_of_previous(s:vernac)
```
