### ISSUE TITLE
Newer versions of python missing distutils.spawn

### ISSUE THREAD

**Issue by smore-lore** [whonore/Coqtail#158]
Error:

> ....vim/plugged/Coqtail/python/xmlInterface.py", line 15, in <module>
>     from distutils.spawn import find_executable
> ModuleNotFoundError: No module named 'distutils.spawn'

ref: https://www.python.org/dev/peps/pep-0632/

> For these modules or functions, use the standard library module shown:
> distutils.spawn.find_executable - use shutil.which

Sorry to file issue w/o fix, don't have a chance right now. Greatly enjoying your pluggin!

**Comment by whonore** [comment]
Thanks for reporting, I'm glad you're finding the plugin useful. A temporary workaround might be to install `python3-distutils` as in #157, but it sounds like ultimately I should just switch to using `shutil.which` for python >=3. I'll try to get to that soon.
