### ISSUE TITLE
E492: Not an editor command: CoqStart

### ISSUE THREAD

**Issue by vrama628** [whonore/Coqtail#168]
Hi, I'm new to Coq and Coqtail, and I'm having trouble getting Coqtail working in vim. I use Vundle, so I followed the Vundle instructions; I added `Plugin 'whonore/Coqtail'` to my `.vimrc` in between the `Plugin 'VundleVim/Vundle.vim'` and `call vundle#end()` lines that were already in there. Then I ran `vim +PluginInstall +qa` in my terminal. After this I expected coqtail to be installed and working, but when I open `vim` and enter the command `:CoqStart`, I get the error `E492: Not an editor command: CoqStart`.

I have `coqtop` and `coqide` installed in my shell environment. In vim, when I do `:help coqtail`, it properly brings up coqtail's manual, so it seems like the installation wasn't completely unsuccessful? I'm relatively inexperienced with configuring vim, so I'm not sure what it means for the documentation to be available but the commands not to be available like this. Please let me know if there's any other information I can provide that would be helpful for figuring out how to get Coqtail working in my vim.

**Comment by whonore** [comment]
`:CoqStart` and the other Coqtail commands are only defined when Vim detects that you're editing a Coq (.v) file. Does it work if you open a .v file or if you run `:set filetype=coq`?

**Comment by vrama628** [comment]
It does! That's what I was getting wrong. Thanks!
