### ISSUE TITLE
Command after `From _ Require _.` is not highlighted

### ISSUE THREAD

**Issue by Lysxia** [whonore/Coqtail#17]
The first `Print` is not highlighted here:

```
From foo Require Import bar.

Print 0.
Print 0.
```

**Comment by whonore** [comment]
Thanks, it looks like it's maybe not correctly recognizing the end of the `From _ Require _` part. I'll look into it.

**Comment by whonore** [comment]
Fixed by 3c05d26c26ddce1183521464db1271ae51909f88.

**Comment by Lysxia** [comment]
Yay!
