### ISSUE TITLE
Mappings for Coq{GotoDef,JumpToEnd} clash with Coq{GotoStart,GotoEnd}

### ISSUE THREAD

**Issue by j-hui** [whonore/Coqtail#171]
In particular, `CoqGotoDef` and `CoqJumpToEnd` have the mappings `<prefix>g` and `<prefix>G`, whereas `CoqGotoStart` and `CoqGotoEnd` have the mappings `<prefix>gg` and `<prefix>GG`. The result is that using `CoqGotoDef` incurs a bit of a delay before it realizes the user meant `<prefix>g`.

Not sure if that's a bug or intentional..

**Comment by whonore** [comment]
This is a bug that I'm aware of, but I'd prefer not to change the default mappings without warning. Maybe it would be best to add a warning about the clash for a while first and let users know they can remap the commands.

**Comment by j-hui** [comment]
There are also other potential clashes if you specify a prefix that is another mapping. For example, I use `<C-c>` as my prefix (I came from Proof General), and that clashes with the binding for `CoqInterrupt`.

I've spent some time looking at the code that assigns the mappings, I'm happy to add that warning and make a PR.
