### ISSUE TITLE
Fallback for coqidetop

### ISSUE THREAD

**Issue by Zimmi48** [whonore/Coqtail#179]
Hello,

The Coq platform is now available as a Snap package. As explained in https://github.com/coq-community/vscoq/issues/192, when Coq is installed that way, the name of the `coqidetop` executable is prepended with `coq-prover.` It would be great if Coqtail could test this name as a default fallback when `coqidetop` is not available so that users have a good experience when installing Coq that way.

Thanks!

**Comment by whonore** [comment]
Sure, that should be pretty simple to do.
