### ISSUE TITLE
Change higlighting color.

### ISSUE THREAD

**Issue by JPYamamoto** [whonore/Coqtail#186]
Is there a way to change the highlighting color? It is currently set to green, and I was wondering if it can be set on my vimrc.

**Comment by whonore** [comment]
The color of the sentences that have been/are being checked is controlled by the `CoqtailChecked` and `CoqtailSent` highlight groups respectively.
You can customize them in your vimrc with something like
```vim
hi CoqtailChecked ctermbg=55 guibg=Purple
```

**Comment by JPYamamoto** [comment]
I actually had to define it inside a g:CoqtailHighlight function, but your comment set me on the right path. Thank you.

**Comment by whonore** [comment]
Actually, would you mind telling me a bit more about your setup so I can try to figure out why setting the highlighting inside `g:CoqtailHighlight` is necessary? The default highlighting uses `hi def` so it shouldn't override any custom highlighting you set in your vimrc, but although this is the case for me, it doesn't seem to work for everyone.

In particular, could you tell me:
- what version of Vim/NeoVim you use (`vim --version` or `nvim --version`)
- how you installed Coqtail (e.g. vim-plug, vundle, native vim package, etc)
- and, if you have time to check, whether you still have this problem (needing to define it inside `g:CoqtailHighlight`) using a minimal vimrc with no plugins besides Coqtail

**Comment by JPYamamoto** [comment]
- I'm using neovim 0.4.3
- I installed Coqtail with vim-plug.
- Actually I tried to use a minimal vimrc and it worked without defining it inside `g:CoqtailHighlight`, so I guess there's something weird going on with my plugins.

Let me know if I can be of further help.

**Comment by whonore** [comment]
Thanks for the information, it sounds like maybe one of your other plugins is interfering somehow. Could you list which you have installed so I can try to track down which one is the problem and see if it's a bug on Coqtail's side or theirs?

**Comment by j-hui** [comment]
I think I figured out why. For whatever reason, setting a `colorscheme` clears any user-defined highlighting (I encountered this when playing with another plugin).

The fix is to add an autocommand that hooks into colorscheme changes, i.e.

```viml
    augroup CoqtailHighlights
      autocmd!
      autocmd ColorScheme *
            \   highlight def CoqtailChecked ctermbg=236
            \|  highlight def CoqtailSent  ctermbg=237
    augroup END
```

You can also be more specific with your highlighting and add highlighting for each colorscheme by using `ColorScheme <colo-name>`.

**Comment by j-hui** [comment]
I could reproduce the issue with the following minimal vimrc, without a custom colorscheme:

```viml
 set nocompatible
 filetype plugin indent on
 syntax enable
 call plug#begin('~/.vimplugins/plugged')
  Plug 'whonore/coqtail'
    highlight def CoqtailChecked ctermbg=236
    highlight def CoqtailSent  ctermbg=237
 call plug#end()
 colorscheme ron
```

Replacing the two `highlight` invocations with the `augroup` block earlier fixes the issue (i.e., I don't see default highlight background anymore).

**Comment by whonore** [comment]
Oh yea, I remember now. I even left a [comment](https://github.com/whonore/Coqtail/blob/master/syntax/coq.vim#L50) to remind myself. I'll update the documentation to explain and suggest the autocommand solution. I'll also undocument `g:CoqtailHighlight`, but I won't remove it from the code yet so it doesn't break for anyone currently relying on it.
