### ISSUE TITLE
Coqtail doesn't add current directory to LoadPath?

### ISSUE THREAD

**Issue by cpitclaudel** [whonore/Coqtail#192]
(This is a report from one of my students)

Assume the following setup:

```
echo "Definition a := 1." > A.v
echo "Require A." > B.v
coqc A.v
```

In that setting `coqtop < B.v` works, and so does `coqc B.v` or running B in CoqIDE, but Coqtail doesn't seem to add the current directory to the loadpath, so the `Require` fails.

Is that on purpose / expected?
Thanks!

**Comment by whonore** [comment]
Which version of Coq is the student using and which commit of Coqtail? Is there a `_CoqProject` file? That example worked for me when I checked with both the Coqtail master branch and v1.3.0 tag and several recent versions of Coq.

**Comment by cpitclaudel** [comment]
8.13, Coqtail from git, and there is a CoqProject but it doesn't mention `.`.   Thanks a lot for giving it a try; I will investigate further next time the student comes to office hours.  Starting vim with  `COQPATH=$(pwd)` also fixed the issue for the student.

**Comment by yamaguchi1024** [comment]
I'm the student @cpitclaudel mentioned. Thank you both for bringing this up!
Coq version is 8.13.0.
The reproducer that Clément gave worked fine on my setting. I tried to make a small reproducer, but couldn't find out what exactly was causing the problem. Below is the description of how I ran into the problem:
```
git clone https://github.com/mit-frap/spring21
cd spring21
make -C frap lib
cd pset01_ProgramAnalysis
make
vim Pset1Implementation.v
(Run Coqtail)
```
This gives me `Unable to locate library Pset1Signature. (While searching for a .vos file.)` error.

**Comment by whonore** [comment]
Hm, I'm still not seeing any errors following those steps. Could you pull the most recent Coqtail commit and try the following (after opening Pset1Implemenation.v):
```vim
:CoqToggleDebug
:CoqStart
:e <C-R>=b:coqtail_log_name
```
Then copy the second line and paste it here. It should look something like:
```
2021-02-26 09:56:40,295: ('/path/to/coqidetop', '-main-channel', 'stdfds', '-async-proofs', 'on', '-async-proofs-command-error-resilience', 'off', '-async-proofs-tactic-error-resilience', 'off', '-topfile', '/path/to/spring21/pset01_ProgramAnalysis/Pset1Implementation.v', '-R', '/path/to/spring21/frap/', 'Frap')

```

**Comment by yamaguchi1024** [comment]
I pulled the most recent Coqtail, and it just worked fine with import! Thank you for fixing this!

**Comment by whonore** [comment]
Interesting, it must have been some earlier commit because the last one just added an extra debugging line. Anyway, I'm glad it works now.

**Comment by cpitclaudel** [comment]
Thanks everyone! :)
