### ISSUE TITLE
Display number of remaining subgoals

### ISSUE THREAD

**Issue by Lysxia** [whonore/Coqtail#20]
Currently after solving a subgoal, the goals window only shows `0 subgoals`, i.e., you only see subgoals under the current bullet. When you're done with a bullet, it would be nice to know whether more bullets remain (and ideally, which bullet is next).

```coq
Goal True /\ False.
Proof.
  split.
  - constructor.
    (* Says "0 subgoals", but there is still the False branch of the other "-" bullet left. *)
```

**Comment by whonore** [comment]
1c94251af5c3503fec4b27ad7e399b59b1790427 now tells you the next goal and bullet to use as well as how many goals are unfocused, admitted, and shelved.

**Comment by Lysxia** [comment]
That works great!
