### ISSUE TITLE
neovim support is broken (neovim bug?)

### ISSUE THREAD

**Issue by tomtomjhj** [whonore/Coqtail#203]
In neovim (tested with 0.4.4 and nightly + pynvim 0.4.3) and coqtail 1.4.0, `g:coqtail#supported` is set to 0 because `py3eval()` returns `v:null`.
https://github.com/whonore/Coqtail/blob/38001abe19df842a56e8762166502ae45ea8beda/autoload/coqtail/compat.vim#L21-L24

Interestingly, `py3eval()` always return `v:null` when it's called for the first time after starting neovim, and the subsequence calls returns the proper value. So the users can bypass this by adding `call py3eval('0')` at the top of their `init.vim`.

This is definitely a neovim bug. I'll file an issue there.

**Comment by whonore** [comment]
That's strange, but at least there's an easy workaround. It also seems like the warning message that Coqtail requires Python 3 doesn't get printed either. In fact I don't see any messages from `echom` that are called during loading no matter where I put them. Do you know if this is also a neovim issue or is there an alternate preferred way of reporting error messages during plugin loading?

**Comment by tomtomjhj** [comment]
link to the neovim issue https://github.com/neovim/neovim/issues/14438 

---

>  don't see any messages from echom that are called during loading

https://github.com/neovim/neovim/issues/9314 The issue is that nvim has `set shortmess+=F` by default, which silences messages from autocmds. I'm not sure why that is the default. `:throw` seems to be suitable for this case.
