### ISSUE TITLE
Misaligned error highlighting

### ISSUE THREAD

**Issue by Lysxia** [whonore/Coqtail#21]
The red highlighting when an error occurs starts a few characters too early. 

![sc-2019-04-25T19:43:17-04:00](https://user-images.githubusercontent.com/2515201/56774923-a73a1b00-6792-11e9-9bd7-b0381dafa6b3.png)

**Comment by whonore** [comment]
I think this has something to do with whitespace being stripped before being sent to coqtop so the reported error location is slightly offset.

**Comment by whonore** [comment]
This should be fixed now by 24e16420f88616080536af5123015fb2d2000a23.

**Comment by Lysxia** [comment]
Thanks, that works!
