### ISSUE TITLE
CoqGotoDef for identifiers ending with single quote fails in some cases

### ISSUE THREAD

**Issue by tomtomjhj** [whonore/Coqtail#217]
Coqtail adds `'` to the keyword character in the syntax definition. So this search pattern correctly matches identifiers ending with `'`.
https://github.com/whonore/Coqtail/blob/570c13efcab0191e1ab3837c712c711944cbb21d/python/coqtail.py#L1093-L1094

However, tag searching itself does not set filetype when reading the file. So, if the file containing the query has not been loaded by vim yet, searching for an identifier ending with `'` fails.

**Comment by whonore** [comment]
It seems that just setting the global value of `iskeyword` to include `'` is enough at least for the case I'm testing. Could you confirm that #218 fixes the problem on your end too?

**Comment by tomtomjhj** [comment]
#218 works well for me. 

> From experimenting a bit it looks like vimgrep only takes iskeyword into account if the buffer is active (displayed in a window). 

It seems that `vimgrep` and tag searching take account of the filetype's `iskeyword` even when the buffer is in `:h hidden-buffer` state. Does your configuration have `set hidden`?

**Comment by whonore** [comment]
I don't have `set hidden` in my config so when a buffer isn't on screen it's `inactive` I guess? `h: inactive-buffer` says options are remebered if the file was once loaded, but `vimgrep` wasn't finding identifiers with `'` even if I loaded the file first and then switched away to a different one. There's probably something I'm misunderstanding about how this works, but from what I was seeing it doesn't seem like `vimgrep` takes the buffer-local value of `iskeyword` into account when the buffer is inactive.

In any case, if #218 works and you don't have a cleaner solution then I'll just go with that for now.

**Comment by tomtomjhj** [comment]
Yeah Vim's documentation on this topic is quite confusing. Anyway, I think #218 is the best solution for now.
