### ISSUE TITLE
Highlighting Coercion commands

### ISSUE THREAD

**Issue by Lysxia** [whonore/Coqtail#22]
Simple example:

```coq
Coercion Tyvar : tyvar >-> ty.
```

Everything after `Coercion` gets highlighted in red.

**Comment by whonore** [comment]
Fixed by 1218d292529e4561f09a9dd3df6f0848ed3b5d9b. At least mostly. It's a little tricky to capture all the allowed variants (`Coercion ... : _ >-> _` and `Coercion ... := ...`) with Vim's syntax matching so things might not look entirely right if you have weird formatting like extra line breaks.
