### ISSUE TITLE
Is there a way to change indentation style?

### ISSUE THREAD

**Issue by ju-sh** [whonore/Coqtail#246]
By default coqtail seems to indent 'branches' (not sure if that's the right term) like

```
Inductive exmpl :=
  | hi
  | hello.
```

with an indentation level before the `|`s.

Even if we try to remove the indentation, the next 'branch' would retain the same indentation level (probably how it's supposed to work) like

```
Inductive exmpl :=
  | hi
```

changed to

```
Inductive exmpl :=
| hi
```

becoming

```
Inductive exmpl :=
| hi
  |
```

on hitting beginning to write a new line.

Is there a way to set the default indentation style to one without spaces before the `|`s? Like

```
Inductive exmpl :=
| hi
| hello.
```

I'm on:
 - Coq 8.12.2
 - Coqtail from master branch on Tue Jan 26 16:35:35 2021 -0500

**Comment by whonore** [comment]
There is not currently an option to control that, but it should be relatively easy to add so I'll try to do that soon.

**Comment by whonore** [comment]
The PR I just merged added an option called `g:coqtail_inductive_shift` that should do what you want if you set it to 0.

**Comment by ju-sh** [comment]
Thanks, it works!

At first I thought I set the option wrong when I hit enter after typing

```
Inductive exmpl :=
```

as the cursor moved to a position after a level of indentation. But when I typed the `|` it went back.

```
Inductive exmpl :=
| 
```
