### ISSUE TITLE
Getting stuck during execution

### ISSUE THREAD

**Issue by ju-sh** [whonore/Coqtail#247]
I was trying to run the following:

```
Require Import String.

Definition str_of_ascii (a : Ascii.ascii) : string := String a EmptyString.

(* Getting stuck while executing next line *)
Compute str_of_ascii (Ascii.ascii_of_nat 0).
```

But the execution seems to be getting stuck while executing the last line.

This executes without any problem in coqtop and proof-general.

Is this behaviour just for me? Why could this be happening?

- Coq 8.12.2
- Coqtail from master branch on Tue Jan 26 16:35:35 2021 -0500

**Comment by whonore** [comment]
I also observe the same behavior with Coq 8.14.0. I think what's happening is `str_of_ascii (Ascii.ascii_of_nat 0)` evaluates to a string of just the null character, which is causing some string handling somewhere to break. 

I'm not sure yet if this is a bug on the Coq side, or if Coqtail needs to be more careful in parsing the output from coqtop. If I run this example with CoqIDE I get a "coqidetop died badly" message, so they're doing something wrong too. Interestingly, if you change `0` to `1` then CoqIDE no longer crashes, but Coqtail still hangs.

**Comment by ju-sh** [comment]
In coqide 8.12.0, this runs without hanging or crashing (didn't try upgrading as it would take a long time).

The `Compute str_of_ascii (Ascii.ascii_of_nat 0).` just gives `string` as  info output.

Then possibly the problem was introduced after that?

(This was the first time I used coqide 😬.)

**Comment by ju-sh** [comment]
And using `coqc` (version 8.12.2 though) directly on a file with just those three lines ran okay too.

```
$ coqc input.v
     = ""%string
     : string
```
