### ISSUE TITLE
Tags for versions 1.5.2 and 1.6.0 have not been pushed to GitHub

### ISSUE THREAD

**Issue by gullcomb** [whonore/Coqtail#249]
Commits ed60e5ecc415141b3b85eece94184db3a3995073 and 8fe30d125b7a6dfbff66714784f8996002a69fdf reference versions 1.5.2 and 1.6.0 respectively, but no such tags have been pushed to the GitHub repository. Consequently, the following links are dead:

https://github.com/whonore/Coqtail/blob/c8ffb3d358e85211b17dd18df6007e3be1bd2569/CHANGELOG.md?plain=1#L287-L288

@whonore Did you forget to push tags `v1.5.2` and `v1.6.0`?

**Comment by whonore** [comment]
Thanks for reminding me. I just pushed them.
