### ISSUE TITLE
Highlight Equations command

### ISSUE THREAD

**Issue by Lysxia** [whonore/Coqtail#25]
I'm trying out the Equations package, which introduces a new `Equations` command, and of course it would be nice to have it properly highlighted.

- `Equations`
- `Derive Signature for _type_`

Naturally, this also raises the more general question of what can be done about syntactic extensions outside of a limited "standard" core.

In the case of Equations, it seems to substantially improve dependently-typed programming in Coq to the point that I would consider it standard.
PG already highlights the `Equations` keyword but I don't know much more than that.

In general, for less essential packages, it makes sense to not support them individually. But unknown commands are currently highlighted in red, while it might be a good idea to not highlight them at all, as a more neutral choice.

**Comment by whonore** [comment]
I agree it seems standard enough to add it. I can try doing it soon or you could submit a pull request. 

As for unrecognized commands, I agree using something less scary than the error color would be a good idea.

I think at some point a fairly significant overhaul of the syntax highlighting is in order. There’s a lot of partial code duplication and valid syntax that isn’t properly recognized.
