### ISSUE TITLE
Implicit Type (x : string) crashes Coqtail

### ISSUE THREAD

**Issue by lgaeher** [whonore/Coqtail#252]
The following code in an otherwise empty Coq file reproducibly crashes Coqtail for me:
```
From Coq Require Import String.
Implicit Types (x : string).
Set Printing All.
```
I haven't been able to reproduce this with any other types than `string`.
The `Set Printing All.` first causes Coqtail to get stuck. Pressing Ctrl+c  then produces some AssertionErrors that are shown in vim or crashes vim altogether with an error like
```
Vim: Caught deadly signal ABRT
Vim: preserving files...
malloc_consolidate(): unaligned fastbin chunk detected
Vim: Double signal, exiting
Traceback (most recent call last):
File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread[1]    154337 segmentation fault (core dumped)
```
(The `Set Printing All` specifically does not seem to be relevant -- the same occurs e.g. with `Set Typeclasses Debug.`).

This applies to both Coq 8.13.2 and Coq 8.14.0. My Python version is 3.10.1.

**Comment by tomtomjhj** [comment]
I had similar issue on NeoVim. IIRC it hangs somewhere around
 https://github.com/whonore/Coqtail/blob/c8ffb3d358e85211b17dd18df6007e3be1bd2569/python/coqtop.py#L346-L351

**Comment by tomtomjhj** [comment]
Note that `Eval lazy in forall x, x.` fails with `Implicit Types (x : string).`

https://github.com/whonore/Coqtail/blob/c8ffb3d358e85211b17dd18df6007e3be1bd2569/python/xmlInterface.py#L304


Changing the `noop` command to something that doesn't depend on the context fixes the issue.
For example,

```python
        self.noop = "Eval lazy in Type."
```
