### ISSUE TITLE
Unable to locate library. (While searching for a .vos file.)

### ISSUE THREAD

**Issue by jvolden** [whonore/Coqtail#257]
Having same issue as #192 with the same source material.

"Unable to locate library Pset1Signature. (While searching for a .vos file.)"

Here is the output you asked about in the previous ticket:
2022-01-26 02:21:17,870: ('/snap/bin/coqidetop.opt', '-main-channel', 'stdfds', '-async-proofs', 'on', '-async-proofs-command-error-resilience', 'off', '-async-proofs-tactic-error-resilience', 'off', '-topfile', '/home/jon/projects/spring21/pset01_ProgramAnalysis/Pset1Implementation.v', '-R', '/home/jon/projects/spring21/frap/', 'Frap')

I was using 8.12.?? on WSL2 via normal apt install through Ubuntu. Removed it and installed the snap version to get 8.13.2. Both version threw the same error.

**Comment by jvolden** [comment]
I'm going to close this. Its doing the same thing on multiple IDEs.

**Comment by whonore** [comment]
Sorry you're encountering this issue, but I'm not able to reproduce it on my end and the `coqidetop` arguments look correct. Are you sure `Pset1Signature` is compiled, can you see `Pset1Signature.vos` in the `pset01_ProgramAnalysis` directory?

**Comment by jvolden** [comment]
Thank you for responding. This is a case of me not knowing what I'm doing. For this set of problems I assumed the instructions for running make to compile the book did so for all problem sets. But it doesn't.

If anyone finds this and has the same issue, you have to run make in each problem set directory.
