### ISSUE TITLE
Failed to launch Coq

### ISSUE THREAD

**Issue by automaton777** [whonore/Coqtail#289]
Running Void Linux, Coq 8.15.1, Neovim 0.70, pynvim 0.3.1. When I start Coq in Neovim I get the message "Failed to launch Coq. Could not find coqidetop in /bin. Perhaps you need to set g:coqtail_coq_path or g:coqtail_coq_prog." coqtop is installed in /bin (CoqIDE is not installed). When I explicitly specify the location of coqtop by adding `let g:coqtail_coq_prog = 'coqtop'` to my init.vim, I instead get the message: 

> Failed to launch Coq. Coqtail experienced an unexpected error. Please report at https://github.com/whonore/coqtail/issues.
> Welcome to Coq 8.15.1
>
> Coq <

When I look at the logs generated by running Neovim in verbose mode, I see the following immediately before "Failed to launch Coq":

`continuing in function coqtail#start`

and this following the "Coq <" prompt:

`Error detected while processing function coqtail#start[32]..coqtail#stop[2]..<SNR>28_cleanup:`
`line 6:`
`E216: No such group or event: coqtail#Sync * <buffer>`

I have no issues running coqtop itself.

**Comment by whonore** [comment]
Even if you don't use CoqIDE Coqtail needs `coqidetop` to be installed because it understands the XML protocol where `coqtop` does not for recent versions of Coq. How did you install Coq?

**Comment by automaton777** [comment]
Thanks. I installed Coq from the main Void repository. I have now installed CoqIDE with opam and Coqtail works :) Maybe it would be worth listing CoqIDE/coqidetop as a dependency in your README?
