### ISSUE TITLE
Requires Python 3.6 error in Neovim

### ISSUE THREAD

**Issue by fifty-six** [whonore/Coqtail#304]
The README says this is usable with `neovim` if it's compiled with `+python3`, but neovim can't be compiled be with python anymore afaik (https://github.com/neovim/neovim/issues/2561). I've done `pip install neovim` for the IPC and `:checkhealth` shows the Python 3 provider there but I still get the error of `Requires Python 3.6 or later...`

![image](https://user-images.githubusercontent.com/10470872/187538241-206509c4-180b-4e98-a333-0616fbd7d00a.png)

![image](https://user-images.githubusercontent.com/10470872/187538284-95ab50ca-b5c5-4758-8ca9-f833b1811da0.png)

**Comment by whonore** [comment]
Thanks for reporting. From your screenshot it looks like it's saying python support is disabled even though it can find an executable, so maybe it's something in your configuration or how you installed it? I'm not a NeoVim user, but I just confirmed that Coqtail does work if I install it through `nix shell nixpkgs#neovim`.

I'd suggest trying the following:
- Try using a minimal `init.vim` that only loads Coqtail to rule out interference from other settings or plugins.
- Confirm that `has('python3')` returns true and `call py3eval(0)` works.

If those don't work then it may be something with how you're installing.

**Comment by fifty-six** [comment]
Ah yeah a minimal init.lua worked, thank you for responding so quickly!
