### ISSUE TITLE
Comments with leading * cannot be joined using J

### ISSUE THREAD

**Issue by bn-peters** [whonore/Coqtail#305]
Joining comments with leading `*` deletes the line involved. To reproduce, install Coqtail (with default configuration) and create the following file:
```
(* test [CURSOR] 
* test *)
```
Pressing `J` to join the lines leads to
```
(* test
```

This does not happen if the second line does not start with `*`.

**Comment by whonore** [comment]
Thanks for reporting. After a little bit of experimentation, I've narrowed this down to something related to the `j` flag in `'formatoptions'`. I'll have to keep looking to find the exact problem, but I'm guessing it's something to do with `'comments'`.
