### ISSUE TITLE
test with coq master

### ISSUE THREAD

**Issue by andres-erbsen-sifive** [whonore/Coqtail#33]
#31 adds support for an unreleased version of coq, but no tests. I have been having an okay time testing bedrock2 against coq master using this script: https://github.com/mit-plv/bedrock2/blob/master/.builds/nixos-coqmaster.yml

**Comment by andres-erbsen-sifive** [comment]
in fact, if we had working tests on coq master, we could probably make all future versions "supported" in the sense that the plugin would try to work with them (but probably still issue a warning).

**Comment by whonore** [comment]
Cool, thanks. I'll see if I can adapt that script to my CI setup.
