### ISSUE TITLE
Breaking with after/syntax directory

### ISSUE THREAD

**Issue by mizlan** [whonore/Coqtail#332]
I tried adding the following to `~/.config/nvim/after/syntax/coq.vim`:

```vim
syn match coqprime "\<forall\>" conceal cchar=∀
syn match coqprime "\<exists\>" conceal cchar=∃
syn match coqprime "\<fun\>" conceal cchar=λ

hi link coqprime coqKwd
hi! link Conceal coqKwd

setlocal conceallevel=1
```

When I open up a Coq file, nothing is concealed. However, if I disable Coqtail, it works. So I am wondering if Coqtail is somehow interfering with this. It seems like Coqtail is being a good steward and using `syntax/coq.vim`, and so I am confused why it isn't working. Maybe you can give it a quick go?

**Comment by whonore** [comment]
Thanks for reporting this. There are two issues that prevent your syntax rules from working.

First, you have to add `coqprime` to the `coqTerm` syntax group since most of the top-level syntax rules use `contains=@coqTerm`.
```vim
syn cluster coqTerm add=coqprime
```

Second, `forall` and `fun` are defined as `keyword`s in Coqtail's `syntax/coq.vim`, which have higher priority than `match`es (`:h syn-keyword`). As far as I know, the only way to have your rules take precedence is to also define them as `keyword`s.
```vim
syn keyword coqprime forall conceal cchar=∀
syn keyword coqprime exists conceal cchar=∃
syn keyword coqprime fun conceal cchar=λ
```

**Comment by mizlan** [comment]
Thanks for your help. I had a suspicion about the latter "keyword" priority vs. match part, but I had no idea about syntax groups/clusters. Thanks for showing me, and thanks for teaching me about syntax groups!

**Comment by mizlan** [comment]
Oh: there is a funny issue now where the concealed symbols have `Normal` bg when they instead should have `CoqtailChecked`:

<img width="615" alt="Screen Shot 2023-11-06 at 2 54 30 PM" src="https://github.com/whonore/Coqtail/assets/44309097/41c0534c-e494-48ee-b1f7-0ba9f420b995">

I have yet to look into this but might you know how to resolve this?

**Comment by whonore** [comment]
I'm not sure how or if there's a way to fix that. The `CoqtailChecked` highlighting is added with `matchadd`, which the Vim docs say should always have priority over `syntax` highlighting (`:hi`), but it seems like conceal may work differently. I found these links confirming other people have this issue, but no solutions as far as I can tell.

https://stackoverflow.com/questions/24131474/can-i-fix-conceal-highlight-group-background-in-highlighted-lines
https://vi.stackexchange.com/questions/26742/how-to-overwrite-the-conceal-background-color-with-line-color

**Comment by mizlan** [comment]
I see, thanks! I think I will stick with not concealing; I don't even know how I got so committed to this rabbithole in the first place. Thanks for your help.
