### ISSUE TITLE
[Syntax] Is there a lack of support for math symbol shortcuts?

### ISSUE THREAD

**Issue by hyunsooda** [whonore/Coqtail#333]
Does Coqtail provide shortcuts for mathematical symbols like ∀ and ∃? I observed that the [agda-vim](https://github.com/ashinkarov/nvim-agda) plugin natively supports these symbols. Thanks.

**Comment by tomtomjhj** [comment]
No built-in support, but there are some tips documented here: https://github.com/whonore/Coqtail/tree/main#latexunicode-input

**Comment by hyunsooda** [comment]
Got it. Thank you.
