### ISSUE TITLE
Detach panels from neovim instance

### ISSUE THREAD

**Issue by Ddystopia** [whonore/Coqtail#334]
Is there a way to detach panels to separate neovim instances? It could be very handy with multiple monitors or when someone uses tiling managers - they are much better at window management then neovim itself.

I've read help but didn't find anything like that.

**Comment by whonore** [comment]
There isn't currently an option to do that, but it seems like a potentially useful feature. I'll look into it.

**Comment by whonore** [comment]
As far as I can tell, this isn't currently possible in neovim, but there's some relevant discussion in neovim/neovim#2161 and neovim/neovim#13504. It might be possible to hack something together using vim/neovim's remote editing features (`:h client-server`), but I think that would be more complicated than I'm willing to try at the moment.

**Comment by rwmpelstilzchen** [comment]
[This](https://github.com/neovim/neovim/discussions/29994#discussioncomment-10258771) might be relevant here. No TUI support yet :-(
