### ISSUE TITLE
Coqtail does not officially support your version of Coq (8.19.0)

### ISSUE THREAD

**Issue by foxyseta** [whonore/Coqtail#341]
When launching Coqtail, I get:

```
Coqtail does not officially support your version of Coq (8.19.0)
```

Despite https://github.com/whonore/Coqtail/pull/336.

**Comment by wntress** [comment]
Reinstall it. That fixed it for me

**Comment by foxyseta** [comment]
Reinstall Coq? From 0?

**Comment by wntress** [comment]
The plugin.

**Comment by foxyseta** [comment]
Yep, that was enough apparently

**Comment by foxyseta** [comment]
Thanks!

**Comment by whonore** [comment]
I’m glad that fixed the problem. I expect you just didn’t have the most recent version installed. For the future, depending how you manage your plugins, there should be a way to update them without fully reinstalling. For example, VimPlug has `:PlugUpdate`, or you can always just go to whatever directory they’re in (e.g., `.vim/bundle`, `.vim/pack`) and `git pull` the latest version.

**Comment by foxyseta** [comment]
Actually, I did have the most recent version installed, but through an uodate rather than a clean install. The clean install is what fixed it for me, not the update.
