### ISSUE TITLE
goal display shows first lines instead of last lines

### ISSUE THREAD

**Issue by andres-erbsen-sifive** [whonore/Coqtail#36]
```coq
Goal True.
  pose proof (eq_refl 0).
  do 500 match goal with H: ?x = ?x |- _ => pose proof (eq_refl (S x)) end.
  (* "True" should be visible in the goal buffer at this point, as in coqide and PG *)
Abort.
```

**Comment by whonore** [comment]
It actually leaves the window state untouched (same top line, cursor position, etc) and only scrolls up if the context shrinks causing the bottom of the window to be below the last line. I find this useful sometimes if I want to see how a hypothesis somewhere in the middle changes between steps as long as the size of the context doesn't change too drastically. 

It would be possible to add a command to make the goal display jump to the first goal or something, or make it an option to do it automatically. It does still leave the question of where exactly to scroll. Do you make sure you can see the end of the goal by putting it on the last line, or show the top of the goal, or some compromise to include part of the context, etc.

**Comment by andres-erbsen-sifive** [comment]
yeah, this is an awkward one. In my use case, the context is too large to read anyway (although tracking a particular hypothesis might be useful); and I use goal selector `!` so that I always have only one goal. I think in that setting, PG's behavior of scrolling to the end of the buffer is acceptable. Although jumping to the beginning of first goal may be nicer, even with a single goal, if that goal is too large to be shown at once.

**Comment by andres-erbsen-sifive** [comment]
refining this suggestion: let's make (an option that makes) the bottom of the buffer align with the line after the end of the first goal -- either the title of the next goal, or a "no next goal" indicator (I meant the dependent evars line, but apparently it is not a thing anymore).

**Comment by andres-erbsen-sifive** [comment]
perhaps even less intrusive would be a keyboard shortcut to seek the goal display so that the end of the first goal lines up with the end of the visible part of the buffer. It is still just slightly beyond my current skill/affordance to implement this right away, but I think I could with a couple of pointers on how to access the goal buffer contents and how to seek its view.

**Comment by whonore** [comment]
The goal buffer is stored in `b:coqtail_panel_bufs['goal']`. [`ScrollPanel`](https://github.com/whonore/Coqtail/blob/master/autoload/coqtail.vim#L154) and [`restore_panel`](https://github.com/whonore/Coqtail/blob/master/python/coqtail.py#L555) may be useful as references for how to manipulate the buffer's view. I may also have some time next week to work on this if you don't get to it before then.
