### ISSUE TITLE
:CoqJumpToEnd hangs neovim if Coqtail hasn't been fired yet.

### ISSUE THREAD

**Issue by TairanLee** [whonore/Coqtail#360]
Coq 8.19.2  
nvim 0.9.5

Anytime if `:CoqJumpToEnd` runs before `:CoqStart`, the neovim session will hang, accepts no input and possibly damage the file contents.  

It sounds silly but in fact I mapped some shortcuts for these instructions.  
And sometimes I forgot to even fire up Coqtail first, so I encountered this.  

Thanks a lot for this tool, it's really helpful !

**Comment by whonore** [comment]
This was tricky, thanks for catching it. I believe #361 fixes the problem. I've tested it some on my end, but I'd appreciate it if you could try it out a bit and make sure it seems ok.

**Comment by TairanLee** [comment]
Checked on `NVIM v0.10.0` & `NVIM v0.9.5` in two different systems, both work fine now.  
Thank you very much for this quick fix !
