### ISSUE TITLE
Close brace treated as admit

### ISSUE THREAD

**Issue by whonore** [whonore/Coqtail#37]
```
Goal False.
Proof.
  { idtac. }
Admitted.
```
Coqtail let's this go through as if `}` was `admit. }` but coqc gives the error `Error: This proof is focused, but cannot be unfocused this way`. Coqtail also gives this error for empty braces `{ }`.

**Comment by andres-erbsen-sifive** [comment]
fyi coqide also lets this go through as if the close brace was an admit, and even colors the close brace orange.

**Comment by andres-erbsen-sifive** [comment]
I am looking at https://coq.inria.fr/refman/addendum/parallel-proof-processing.html?highlight=async%20bullet#proof-blocks-and-error-resilience but it is not clear to me whether the options there would help

**Comment by whonore** [comment]
It looks like it can be disabled with `-async-proofs-tactic-error-resilience off`.
