### ISSUE TITLE
feature request: incremental message output

### ISSUE THREAD

**Issue by andres-erbsen-sifive** [whonore/Coqtail#39]
the effect should be visible on a file like this one:

```coq
Goal True.
  do 5 (idtac "."; do 400 pose I).
Abort.
```

A real use case would be hunting down the reason why typeclass resolution doesn't terminate using `Set Typeclasses Debug`.

**Comment by whonore** [comment]
This should be pretty straightforward to implement. I'll try it soon.

**Comment by whonore** [comment]
The incremental output part is fixed, but your particular example still won't work for different reasons (#47, #48).

**Comment by andres-erbsen-sifive** [comment]
Thanks!

**Comment by ju-sh** [comment]
@whonore Is there a way to insert the output of coq inside the current buffer after the line that was just executed?

**Comment by whonore** [comment]
You could just navigate to the Info panel, copy what you want, then move back and paste. I suppose it would be possible to automatically save the most recent line(s) from the Info panel in a register or a variable or something. What is the use case you have in mind?

**Comment by ju-sh** [comment]
Yeah, I'm copying from the info panel now. But it feels like a repetitive task for doing the copy every now and then. I tried a macro as well, but couldn't find a way to paste the result right after the line that was last executed.

What I was looking for was a way to make the output appear (as a comment) below the command that was last executed. Is there a way?

**Comment by ju-sh** [comment]
For example,

    Check nat.

could become

    Check nat.
    (*
    nat
         : Set
    *)

after execution.

The content that appear in the info panel appearing as a comment right after the block that produced that output.

**Comment by ju-sh** [comment]
And should this discussion be separated out as a new issue?

**Comment by tomtomjhj** [comment]
something like this?
```vim
:CoqJumpToEnd | call append('.', ['(*'] + getbufline(b:coqtail_panel_bufs['info'], 1, '$') + ['*)'])
```

**Comment by ju-sh** [comment]
@tomtomjhj Thanks!
