### ISSUE TITLE
Interaction between 'O' and line with bullet '*'

### ISSUE THREAD

**Issue by vsiles** [whonore/Coqtail#41]
Hi !
I'm not sure it's a bug, more likely a bad interaction with my config. Here is what happens when I open a non Coq file, and I press O on a line starting with *:
https://asciinema.org/a/W0i3Tea9HXtqVIjfSu0YpLsAQ

Here is what happens when I open a Coq file and I press O on a line starting with *:

https://asciinema.org/a/7boKSFb7ExKehoG8DGdudBcHF

Does that ring a bell to anyone ?

**Comment by whonore** [comment]
Is the 'o' flag set in your 'formatoptions' option (`:help fo-table`)?

**Comment by vsiles** [comment]
Indeed it is and removing it seems to fix the issue. I'll read more about that, thank you !

**Comment by vsiles** [comment]
That's definitely it.. sorry for the noise !
