### ISSUE TITLE
_CoqProject support ?

### ISSUE THREAD

**Issue by vsiles** [whonore/Coqtail#42]
Hi ! My project is growing a bit and I'd like to use _CoqProject. Is this supported ?
At the moment I have something very simple with a Makefile (from https://izgzhen.github.io/2016/09/19/coq-dev.html) and a _CoqProject like:
```
-Q . MyPrj
A.v
B.v
```

A.v:
```
Definition t := nat.
```

B.v:
```
Require Import List MyPrj.A.
Definition t := list A.t
```

Building on the command line works:
```
$ make
coq_makefile -f _CoqProject | sed 's/$(COQCHK) $(COQCHKFLAGS) $(COQLIBS)/$(COQCHK) $(COQCHKFLAGS) $(subst -Q,-R,$(COQLIBS))/' > Makefile.coq
Warning: Omitting -o is deprecated

make -f Makefile.coq all
COQDEP VFILES
COQC A.v
COQC B.v
```

The overall experience work: I can evaluate A.v and B.v interactively, but I get an error message in B.v: `B.v|1 col 15 error|  Error: Cannot find a physical path bound to logical path matching suffix MyPrj.`

Am I missing something ?

**Comment by whonore** [comment]
_CoqProject is supported and I'm able to interactively step through all of B.v with A.v, B.v, and _CoqProject as you described them. [This line](https://github.com/whonore/Coqtail/blob/de1de720f110bbeab5970d954f1d360cddcd6932/autoload/coqtail.vim#L408) is where the _CoqProject file is located and parsed so you could print out `l:proj_args` to see what arguments Coqtail is passing to Coq.

**Comment by vsiles** [comment]
I'm in `~/coqtest/` on my mac and it displays: `['-Q', '/Users/vsiles/coqtest/', 'MyPrj']`

**Comment by whonore** [comment]
That looks right. If you do `:Coq Print LoadPath` after starting Coqtail is there a line with `MyPrj /Users/vsiles/coqtest`?

**Comment by vsiles** [comment]
it seems to be there

```
MyPrj /Users/vsiles/coqtest
<> /Users/vsiles/.opam/coq/lib/coq/user-contrib
Coq /Users/vsiles/.opam/coq/lib/coq/plugins
Coq.firstorder /Users/vsiles/.opam/coq/lib/coq/plugins/firstorder
Coq.ltac /Users/vsiles/.opam/coq/lib/coq/plugins/ltac
Coq.extraction /Users/vsiles/.opam/coq/lib/coq/plugins/extraction
... lots more Coq.* ....
```

**Comment by vsiles** [comment]
I'll try to remove most of my plugins / conf to see if anything is interfering

**Comment by vsiles** [comment]
Ok, definitely my fault: one of these lines make syntastic crazy:
```
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_ocaml_checkers = ['merlin']
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_python_flake8_exec = 'python3'
```

**Comment by vsiles** [comment]
It's `let g:syntastic_check_on_open = 1`... not sure why

**Comment by vsiles** [comment]
Syntastic is using coqtop to check coq files.. which won't work in here. I disabled it.
