### ISSUE TITLE
gvim cannot load opam env for coq

### ISSUE THREAD

**Issue by linusboyle** [whonore/Coqtail#49]
This is actually not a problem of Coqtail - it works very well in the terminal. But since gvim is not started from an interactive bash session, the opam envs cannot be loaded. I installed coq following the official guide which uses opam, and in this case coq cannot be found.

I'm looking forward to some advice on how to get around this. I have tried to set `$BASH_ENV` in my .vimrc but it didn't work.

**Comment by whonore** [comment]
One option is to try launching gvim from the terminal with `gvim` or `vim -g`. You might also be able to set some environment variables in .vimrc to make it work but I don't know which ones exactly. Probably the better longterm solution is for me to add an option you can set to tell Coqtail where to find the Coq binaries.

**Comment by linusboyle** [comment]
> One option is to try launching gvim from the terminal with `gvim` or `vim -g`. You might also be able to set some environment variables in .vimrc to make it work but I don't know which ones exactly. Probably the better longterm solution is for me to add an option you can set to tell Coqtail where to find the Coq binaries.

@whonore thx, launching gvim from the terminal works fine for me.
