### ISSUE TITLE
Remove the dependency from vimbufsync

### ISSUE THREAD

**Issue by XVilka** [whonore/Coqtail#58]
Like [this fork](https://framagit.org/tyreunom/coquille) of Coquille had done. See this commit: https://framagit.org/tyreunom/coquille/commit/3323c46cfa521395c88ece0b854bbdc9f8399672

**Comment by whonore** [comment]
One potential problem I see with that method is it assumes that the change happened at the cursor, which isn't always the case (e.g. `call append(0, ["abc"])`). Using `TextChanged` does seem like a good solution though if I can find a way of detecting where a change actually occurred. Maybe `:changes` could help?
