### ISSUE TITLE
Highlight From keyword

### ISSUE THREAD

**Issue by Lysxia** [whonore/Coqtail#8]
The `From my_lib Require my_module` syntax doesn't seem to be handled.

**Comment by whonore** [comment]
Thanks for pointing that out, it should be fixed now by 984608fa7be7548ff31d5fb037eac68f39c309dc. The syntax script is based on one that was written quite a while ago so I wouldn't be surprised if many newer Coq features are not correctly supported. Feel free to submit more issues if you find any
