### ISSUE TITLE
Auto-indentation doesn't work for nested bullets

### ISSUE THREAD

**Issue by iambrj** [whonore/Coqtail#89]
As can be seen [here](https://asciinema.org/a/CQBdj111wNKMdu6le8strMvRf), auto-indentation fails for nested bullets. Any fixes would be greatly appreciated.

**Comment by whonore** [comment]
Thanks for reporting. This is actually an issue for the outermost bullet too.
```coq
Goal True /\ True.
Proof.
  split.
  - auto.
    - auto. (* <-- Not matched with previous '-' automatically *)
```
Manually triggering indentation in a way that includes the bullet line and the one before it does work correctly (`=k`, `=ip`, etc.). I'll look into why it doesn't do the same when it's just the incorrectly indented line.

**Comment by iambrj** [comment]
Thank you :)

**Comment by iambrj** [comment]
Hello again,

Just noticed that it still doesn't work for certain bullets. For example
```
Goal True /\ True.
Proof.            
  split.          
  ** auto.        
     ** auto.  (* <-- Not matched with previous '**' automatically *)
```
Fixes would be appreciated :)

**Comment by iambrj** [comment]
Furthermore, it also mismatches bullets. For example `**` is matched with previous `*`.
