### ISSUE TITLE
Double panel on CoqStart

### ISSUE THREAD

**Issue by daniel-sousa-me** [whonore/Coqtail#9]
I have added `au FileType coq CoqStart` to my .vimrc. When I open a .v file I am presented with a duplicate panel. What should I do?

![image](https://user-images.githubusercontent.com/3337865/45964890-46453b80-c027-11e8-9d64-500c14c7be54.png)

**Comment by daniel-sousa-me** [comment]
This doesn't happen if I do :CoqStart manually.

**Comment by whonore** [comment]
It looks like `coqtail#OpenPanels` was getting called twice because of some autocmds. It should be fixed now by d84bc2a18e5fbe9c587cd783ff825b05d86fba29.

**Comment by daniel-sousa-me** [comment]
It's working now. Thank you very much!
