### ISSUE TITLE
NeoVim does not work with CoqTail

### ISSUE THREAD

**Issue by GaurangTandon** [whonore/Coqtail#93]
I use NeoVim, here's version details:

```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```

I am not sure what I am missing. I just installed Coq with Vim Plug (and then did `:PlugInstall`) and created an empty `.v` file and ran `:CoqStart` on it. But it's stuck for more than a minute. I am not sure if it's intended?

(I can share more logs/debug info but I am not sure how to)

**Comment by whonore** [comment]
Thanks for reporting, unfortunately Coqtail doesn't currently support NeoVim (see #68, #13), but I'm working on an update that will make it work (#74). I'll leave this issue open and close it when I finish the update so you get pinged when it's ready.

**Comment by j-hui** [comment]
Thanks for your awesome work @whonore ! I've been on the `async` branch and am excited to see it merged into `master`. I just wanted to note that it seems like NeoVim still has some issues with Coqtail, especially when quitting, but it's beginning to show some signs of life.

**Comment by whonore** [comment]
Thanks, there are still a couple remaining things I need to fix/implement before NeoVim really works, but I'm fairly confident that with the recent restructuring they should be pretty straightforward and I can have them out soon.

**Comment by j-hui** [comment]
let me know if there's anything I can do to help. I haven't had much experience with developing vim plugins, but I know Python and a little vimscript. I love using your plugin and would love to help develop/maintain it how I can.

**Comment by whonore** [comment]
Thanks for the offer and for your interest. I'm hoping to get a start on this this weekend and once it's mostly working what would be really helpful is if you could help beta test it by just trying to use it. And if you're interested in working on the code too I'll try to keep an eye out for smaller tasks that would be manageable without having to learn the whole codebase at once.

**Comment by paldepind** [comment]
I'd be willing to beta-test as well :smile:

**Comment by whonore** [comment]
That's great, thanks. I've only had time to do a little testing, but #103 seems to be mostly working. I'm planning to try using it some more this weekend and hopefully merge it Sunday or Monday.

**Comment by paldepind** [comment]
So it's ready for testing right now? 🙂

**Comment by paldepind** [comment]
I'm not sure if it's Neovim related, but it seems like a have a problem with Coqtail not loading. I've installed Coqtail with Plug as follows:

```
filetype plugin indent on
Plug 'whonore/coqtail', { 'branch': 'neovim' }
```

If I install Coqtail by running `:PlugInstall` then Coqtail is installed and works fine. But, if I close and relaunch Neovim then Coqtail seems to be non-existent, `:help coqtail` doesn't work and none of the `Coq*` commands exists. If I uninstall Coqtail and reinstall it then it works again as long as I don't close Neovim.

**Comment by whonore** [comment]
Just to check, are you also using `plug#begin` and `plug#end`? For example,
```vim
call plug#begin('~/.vim/bundle') " or wherever you put your neovim plugins
Plug 'whonore/coqtail', { 'branch': 'neovim' }
call plug#end()
```

**Comment by paldepind** [comment]
Ops. I had placed the line _after_ the `call plug#end()` in my config. Sorry about that 😅

**Comment by paldepind** [comment]
It's working really well. Things I've noticed thus far:

* Red highlights that I don't know the purpose of:

<img width="369" alt="Screenshot 2020-07-10 at 18 17 03" src="https://user-images.githubusercontent.com/521604/87175956-ab8c1e80-c2d9-11ea-9b15-74cdf8b074cd.png">

* A delay whenever I input a space. As if the editor is waiting for something. If i type a space followed by another character the space and the character appears immediately.

**Comment by whonore** [comment]
Thanks for the feedback.

- The red is just because the syntax highlighting is very ad-hoc and outdated and incomplete in a lot of areas. I have plans (#87) to do a major overhaul at some point, but I'm also happy to accept smaller pull requests for specific fixes like this.
- That sounds like you have a mapping that begins with a space. Could you show me the output of `:imap <SPACE>`? Do you maybe have `<leader>` mapped to `<SPACE>`?

**Comment by j-hui** [comment]
(I also had the issue with `<leader>` being mapped to `<SPACE>`.)

I'm still seeing a few issues with #103. Most notably, when I quit, I get this ugly error message:
```Error detected while processing function coqtail#stop[1]..<SNR>83_call[22]..<SNR>108_evalexpr[9]..<SNR>108_send_wait:
line   19:
Request from non-main thread.
Requests from different threads should be wrapped with nvim.async_call(cb, ...)
  File "/Users/j-hui/.vimplugins/plugged/coqtail/python/coqtop.py", line 449, in capture_err
    print(os.read(fd, 0x10000).decode())
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 186, in write
    self.redirect_handler(data)
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 77, in <lambda>
    sys.stdout = RedirectStream(lambda data: nvim.out_write(data))
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 396, in out_write
    return self.request('nvim_out_write', msg, **kwargs)
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/j-hui/.vimplugins/plugged/coqtail/python/coqtop.py", line 449, in capture_err
    print(os.read(fd, 0x10000).decode())
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 186, in write
    self.redirect_handler(data)
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 77, in <lambda>
    sys.stdout = RedirectStream(lambda data: nvim.out_write(data))
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 396, in out_write
    return self.request('nvim_out_write', msg, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 178, in request
    raise NvimError("request from non-main thread")
pynvim.api.common.NvimError: request from non-main thread
Error detected while processing function coqtail#stop[1]..<SNR>83_call:
line   22:
E171: Missing :endif
```

Asynchronous buffer browsing also does not seem to be working for me (although I'm not sure if that's something you wanted to also support on Neovim).

**Comment by whonore** [comment]
@j-hui Are you sure you're on the right branch? I removed the `print()` call in `capture_err` so you shouldn't get that error message.

**Comment by j-hui** [comment]
...I don't think I'm fully awake yet. I ran `:PlugInstall` instead of `:PlugUpdate`.

Seems to be working well; async also seems to be working too. I'll be using it a bit this weekend, will let you know if I encounter any weird issues.

**Comment by paldepind** [comment]
@whonore Yes, I have leader bound to space. That has not caused problems anywhere else.

**Comment by whonore** [comment]
Coqtail creates insert-mode maps for some of the commands by default (`<leader>cj`, `<leader>cl`, etc). As a workaround you could manually map them to something else by putting something like this in your `.vimrc` or `init.vim`
```vim
imap \cj <Plug>CoqNext
imap \ck <Plug>CoqUndo
imap \cl <Plug>CoqToLine
imap \cT <Plug>CoqToTop
imap \cG <Plug>CoqJumpToEnd
imap \cr <Plug>CoqRestorePanels
imap \cgg <Plug>CoqGotoGoalStart
imap \cGG <Plug>CoqGotoGoalEnd
```

For a better solution I should make an option to disable insert-mode mappings and/or a way to customize the map prefix to something other than `<leader>c`.
