### ISSUE TITLE
QuickChick doesn't work with Coqtail

### ISSUE THREAD

**Issue by jcoveney** [whonore/Coqtail#99]
A minimal example provided by Li-yao:

`Require Import QuickChick.QuickChick.
Require Import Arith.

QuickChick (fun n => Nat.eqb n n).`

Here is a potentially related issue on the QuickCheck github: https://github.com/QuickChick/QuickChick/issues/120

That's for CoqIDE, but I imagine the issue could be similar

**Comment by whonore** [comment]
It seems that coqtop sends the QuickChick messages over `stderr` rather than using the XML protocol. Coqtail does actually print that output just to the regular Vim stdout (visible with `:mes`), but it would probably be better to put it in the Info panel somewhere or make a separate message panel.

**Comment by jcoveney** [comment]
Would it make sense for me to make a bug for the quickchick people to use
the XML protocol? I'm not sure what the proper behavior here is.

**Comment by whonore** [comment]
I guess it wouldn't hurt to mention it. I'm not sure what API is offered to plugins for outputting messages and how much control they have over what coqtop does with it. If it turns out they don't have control over it then maybe it would be worth opening a feature request in Coq instead to expose that option.

**Comment by jcoveney** [comment]
Ok, I made a QuickChick issue, and will make one for Coq if necessary. If you feel you can help clarify what's going on, feel free to comment in the QuickChick issue.

Thank you!

**Comment by jcoveney** [comment]
QuickChick fixed this :)

https://github.com/QuickChick/QuickChick/pull/200/

**Comment by whonore** [comment]
That's great, thanks for reporting it to them. I still want to handle text sent to stderr better, but I'll open that in a separate issue.
